appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a94e246e0700ceddac
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: NDHRdym1XF4VMdJFCnwkTOw/7nc7F9ubtm455Uz5F62/XTymhw5zTgqffW7dlgxbO0HVng1JIZuNqkzL4Y7zrDZiiT5TmlhHR1yWGCKfKGJYuJAa5ExN1o2JfmrGtMvGg9dmm1lBF5YAuDz+BY2uUx0xlXz/U0TWr3CkTQJPhvvpXxmdF9hYsefIXskll6DeY/FFb4z8en11FPVJGrYFOQqdds8yBT9P+Wm276ZTMD93a1hIb26yjwQbFGrch3BlbVGJ5v7dQX5dqH7NCvehSCk/6Jz4/BWb9ebcXDUjLLwCSuJA7d21F/DeTPYmqxpIxHxCbpGV8G34Eh0rY0bdgOtolm6n2ud7yw373XlNN+g0WhxuF3CeWK6/6D4ewPTmBl2IOnmdmphd1CioQOCs/QWCGAei1mKMsla0z71evgZw06Fyc2tdDdLah5mBTL88WdX6cm67YL77opUZ/hlogoMN6jX8MwLFcFGRrsCr+p6PdVu2qOWnhWNc8vOfluLlEV6SWVC1ClJI/GnfYm7ot4zxVi8AP1lWTN16F7jPWtTdbgoLY99epTYdhmzc5TD3Fo00x7HntMXNcSoGfxTzeJZUmSlbgLKvdi+la94XWT07dkvSnog492Ktn6nD2zr0vVBrsZiFaAQ2v6x7tbao3mFMyYoI/ZSmdRF+rQp2XGI=}
